package collector.desktop.networking;

public enum MessageType {
	BEACON,
	
	REQUEST_GET_ALBUM_LIST,
	REQUEST_GET_ALBUM_SCHEMA,
	REQUEST_GET_ITEM_LIST,
	REQUEST_GET_ITEM_CONTENT,
	
	RESPONSE_GET_ALBUM_LIST,
	RESPONSE_GET_ALBUM_SCHEMA,
	RESPONSE_GET_ITEM_LIST,
	RESPONSE_GET_ITEM_CONTENT,
	
	UNKNOWN
}
